# Configuração Nixpacks para EasyPanel
providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "3101"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci --production=false"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[phases.start]
dependsOn = ["build"]
cmds = [
  "npm run start"
] 