# Configuração Nixpacks para EasyPanel
providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "3101"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --include=dev"]

[phases.build] 
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm run start" 