
[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build:production"
]

[start]
cmd = "npm start"
